### PR TITLE
Suppress MySQLi errors so that MythWeb works with PHP 8.1.0.

### PR DESCRIPTION
**Pull request by mymatenige**
Resolves issue #83.

### CODE REVIEW

**Comment by jfabernathy** [comment]
I have also tested these patches and they worked on Debian Testing (Bookworm) which uses php 8.1

**Comment by stuarta** [comment]
I don't believe blindly silencing the errors is the correct course of action

**Comment by paul-h** [comment]
It's not really an error it's more a change in the default behaviour in PHP 8.1 or later. Older version of PHP allowed the query to look for the MythMusic table even if the table didn't exist. Newer PHP version now by default throw an exception if the table does not exist. All the patch does is tell PHP to revert to the old behaviour. All MythWeb wants to know is has the user used MythMusic at all. If they have the the relevant music tables must have been created so it can show the Music options in the MythWeb UI.

Seems a quick and simple fix to me. If MythWeb was still under active development then maybe we could improve it but since it has worked fine the last 200 years give or take :) like it is until the PHP change I don't see any point in that.

**Comment by mymatenige** [comment]
Agreed; the pull request just makes MythWeb behave the same way with PHP 8.1 as it did with 8.0 and previous versions.  The MySQL issues have always been there, it's just that in PHP 8.1 they became exceptions rather than errors; https://php.watch/versions/8.1/mysqli-error-mode.

**Pull request merged**
